# Node
FROM node:17-alpine3.12

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /app

COPY src src
COPY openapi.yml openapi.yml
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY syncServer.js index.js

RUN npm ci --only=production --ignore-scripts

EXPOSE 8080

ENTRYPOINT ["npm", "start"]
