# Node
FROM node:12-alpine3.12

MAINTAINER XWP <technology@xwp.co>

WORKDIR /app

COPY src src
COPY spec/openapi.yml spec/openapi.yml
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY syncServer.js index.js

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
RUN npm install --production

EXPOSE 8080

ENTRYPOINT ["npm", "start"]
